export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
  phoneLength?: number; // Optional: expected phone number length (without country code)
}

export const COUNTRIES: Country[] = [
  // 🇺🇸 United States & Canada
  { name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸', phoneLength: 10 },
  { name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦', phoneLength: 10 },

  // 🇪🇺 Europe
  { name: 'Albania', code: 'AL', dialCode: '+355', flag: '🇦🇱', phoneLength: 9 },
  { name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹', phoneLength: 10 },
  { name: 'Belarus', code: 'BY', dialCode: '+375', flag: '🇧🇾', phoneLength: 9 },
  { name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪', phoneLength: 9 },
  { name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387', flag: '🇧🇦', phoneLength: 8 },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', flag: '🇧🇬', phoneLength: 9 },
  { name: 'Croatia', code: 'HR', dialCode: '+385', flag: '🇭🇷', phoneLength: 9 },
  { name: 'Cyprus', code: 'CY', dialCode: '+357', flag: '🇨🇾', phoneLength: 8 },
  { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flag: '🇨🇿', phoneLength: 9 },
  { name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰', phoneLength: 8 },
  { name: 'Estonia', code: 'EE', dialCode: '+372', flag: '🇪🇪', phoneLength: 8 },
  { name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮', phoneLength: 9 },
  { name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷', phoneLength: 9 },
  { name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪', phoneLength: 10 },
  { name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷', phoneLength: 10 },
  { name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺', phoneLength: 9 },
  { name: 'Iceland', code: 'IS', dialCode: '+354', flag: '🇮🇸', phoneLength: 7 },
  { name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪', phoneLength: 9 },
  { name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹', phoneLength: 10 },
  { name: 'Kosovo', code: 'XK', dialCode: '+383', flag: '🇽🇰', phoneLength: 8 },
  { name: 'Latvia', code: 'LV', dialCode: '+371', flag: '🇱🇻', phoneLength: 8 },
  { name: 'Lithuania', code: 'LT', dialCode: '+370', flag: '🇱🇹', phoneLength: 8 },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺', phoneLength: 9 },
  { name: 'Malta', code: 'MT', dialCode: '+356', flag: '🇲🇹', phoneLength: 8 },
  { name: 'Moldova', code: 'MD', dialCode: '+373', flag: '🇲🇩', phoneLength: 8 },
  { name: 'Montenegro', code: 'ME', dialCode: '+382', flag: '🇲🇪', phoneLength: 8 },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱', phoneLength: 9 },
  { name: 'North Macedonia', code: 'MK', dialCode: '+389', flag: '🇲🇰', phoneLength: 8 },
  { name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴', phoneLength: 8 },
  { name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱', phoneLength: 9 },
  { name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹', phoneLength: 9 },
  { name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴', phoneLength: 10 },
  { name: 'Russia', code: 'RU', dialCode: '+7', flag: '🇷🇺', phoneLength: 10 },
  { name: 'Serbia', code: 'RS', dialCode: '+381', flag: '🇷🇸', phoneLength: 9 },
  { name: 'Slovakia', code: 'SK', dialCode: '+421', flag: '🇸🇰', phoneLength: 9 },
  { name: 'Slovenia', code: 'SI', dialCode: '+386', flag: '🇸🇮', phoneLength: 8 },
  { name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸', phoneLength: 9 },
  { name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪', phoneLength: 9 },
  { name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭', phoneLength: 9 },
  { name: 'Türkiye', code: 'TR', dialCode: '+90', flag: '🇹🇷', phoneLength: 10 },
  { name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦', phoneLength: 9 },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧', phoneLength: 10 },

  // 🌍 Africa, Middle East & India
  { name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫', phoneLength: 9 },
  { name: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿', phoneLength: 9 },
  { name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴', phoneLength: 9 },
  { name: 'Armenia', code: 'AM', dialCode: '+374', flag: '🇦🇲', phoneLength: 8 },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', flag: '🇦🇿', phoneLength: 9 },
  { name: 'Bahrain', code: 'BH', dialCode: '+973', flag: '🇧🇭', phoneLength: 8 },
  { name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯', phoneLength: 8 },
  { name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼', phoneLength: 8 },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫', phoneLength: 8 },
  { name: 'Cameroon', code: 'CM', dialCode: '+237', flag: '🇨🇲', phoneLength: 9 },
  { name: 'Cape Verde', code: 'CV', dialCode: '+238', flag: '🇨🇻', phoneLength: 7 },
  { name: 'Chad', code: 'TD', dialCode: '+235', flag: '🇹🇩', phoneLength: 8 },
  { name: 'Congo, Democratic Republic of the', code: 'CD', dialCode: '+243', flag: '🇨🇩', phoneLength: 9 },
  { name: 'Congo, Republic of the', code: 'CG', dialCode: '+242', flag: '🇨🇬', phoneLength: 9 },
  { name: 'Côte d\'Ivoire', code: 'CI', dialCode: '+225', flag: '🇨🇮', phoneLength: 10 },
  { name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬', phoneLength: 10 },
  { name: 'Eswatini', code: 'SZ', dialCode: '+268', flag: '🇸🇿', phoneLength: 8 },
  { name: 'Gabon', code: 'GA', dialCode: '+241', flag: '🇬🇦', phoneLength: 7 },
  { name: 'Gambia', code: 'GM', dialCode: '+220', flag: '🇬🇲', phoneLength: 7 },
  { name: 'Georgia', code: 'GE', dialCode: '+995', flag: '🇬🇪', phoneLength: 9 },
  { name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭', phoneLength: 9 },
  { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245', flag: '🇬🇼', phoneLength: 9 },
  { name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳', phoneLength: 10 },
  { name: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶', phoneLength: 10 },
  { name: 'Israel', code: 'IL', dialCode: '+972', flag: '🇮🇱', phoneLength: 9 },
  { name: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴', phoneLength: 9 },
  { name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪', phoneLength: 9 },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', flag: '🇰🇼', phoneLength: 8 },
  { name: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧', phoneLength: 8 },
  { name: 'Liberia', code: 'LR', dialCode: '+231', flag: '🇱🇷', phoneLength: 8 },
  { name: 'Libya', code: 'LY', dialCode: '+218', flag: '🇱🇾', phoneLength: 9 },
  { name: 'Madagascar', code: 'MG', dialCode: '+261', flag: '🇲🇬', phoneLength: 9 },
  { name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼', phoneLength: 9 },
  { name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱', phoneLength: 8 },
  { name: 'Mauritania', code: 'MR', dialCode: '+222', flag: '🇲🇷', phoneLength: 8 },
  { name: 'Mauritius', code: 'MU', dialCode: '+230', flag: '🇲🇺', phoneLength: 8 },
  { name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦', phoneLength: 9 },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿', phoneLength: 9 },
  { name: 'Namibia', code: 'NA', dialCode: '+264', flag: '🇳🇦', phoneLength: 9 },
  { name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪', phoneLength: 8 },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬', phoneLength: 10 },
  { name: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲', phoneLength: 8 },
  { name: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦', phoneLength: 8 },
  { name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼', phoneLength: 9 },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦', phoneLength: 9 },
  { name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳', phoneLength: 9 },
  { name: 'Seychelles', code: 'SC', dialCode: '+248', flag: '🇸🇨', phoneLength: 7 },
  { name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱', phoneLength: 8 },
  { name: 'São Tomé and Príncipe', code: 'ST', dialCode: '+239', flag: '🇸🇹', phoneLength: 7 },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦', phoneLength: 9 },
  { name: 'Tanzania', code: 'TZ', dialCode: '+255', flag: '🇹🇿', phoneLength: 9 },
  { name: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳', phoneLength: 8 },
  { name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬', phoneLength: 9 },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪', phoneLength: 9 },
  { name: 'Yemen', code: 'YE', dialCode: '+967', flag: '🇾🇪', phoneLength: 9 },
  { name: 'Zambia', code: 'ZM', dialCode: '+260', flag: '🇿🇲', phoneLength: 9 },
  { name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flag: '🇿🇼', phoneLength: 9 },

  // 🌎 Latin America & the Caribbean
  { name: 'Anguilla', code: 'AI', dialCode: '+1264', flag: '🇦🇮', phoneLength: 7 },
  { name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1268', flag: '🇦🇬', phoneLength: 7 },
  { name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷', phoneLength: 10 },
  { name: 'Bahamas', code: 'BS', dialCode: '+1242', flag: '🇧🇸', phoneLength: 7 },
  { name: 'Barbados', code: 'BB', dialCode: '+1246', flag: '🇧🇧', phoneLength: 7 },
  { name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿', phoneLength: 7 },
  { name: 'Bermuda', code: 'BM', dialCode: '+1441', flag: '🇧🇲', phoneLength: 7 },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', flag: '🇧🇴', phoneLength: 8 },
  { name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷', phoneLength: 11 },
  { name: 'British Virgin Islands', code: 'VG', dialCode: '+1284', flag: '🇻🇬', phoneLength: 7 },
  { name: 'Cayman Islands', code: 'KY', dialCode: '+1345', flag: '🇰🇾', phoneLength: 7 },
  { name: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱', phoneLength: 9 },
  { name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴', phoneLength: 10 },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', flag: '🇨🇷', phoneLength: 8 },
  { name: 'Dominica', code: 'DM', dialCode: '+1767', flag: '🇩🇲', phoneLength: 7 },
  { name: 'Dominican Republic', code: 'DO', dialCode: '+1809', flag: '🇩🇴', phoneLength: 7 },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', flag: '🇪🇨', phoneLength: 9 },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻', phoneLength: 8 },
  { name: 'Grenada', code: 'GD', dialCode: '+1473', flag: '🇬🇩', phoneLength: 7 },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹', phoneLength: 8 },
  { name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾', phoneLength: 7 },
  { name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳', phoneLength: 8 },
  { name: 'Jamaica', code: 'JM', dialCode: '+1876', flag: '🇯🇲', phoneLength: 7 },
  { name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽', phoneLength: 10 },
  { name: 'Montserrat', code: 'MS', dialCode: '+1664', flag: '🇲🇸', phoneLength: 7 },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮', phoneLength: 8 },
  { name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦', phoneLength: 8 },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾', phoneLength: 9 },
  { name: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪', phoneLength: 9 },
  { name: 'St. Kitts and Nevis', code: 'KN', dialCode: '+1869', flag: '🇰🇳', phoneLength: 7 },
  { name: 'St. Lucia', code: 'LC', dialCode: '+1758', flag: '🇱🇨', phoneLength: 7 },
  { name: 'St. Vincent and the Grenadines', code: 'VC', dialCode: '+1784', flag: '🇻🇨', phoneLength: 7 },
  { name: 'Suriname', code: 'SR', dialCode: '+597', flag: '🇸🇷', phoneLength: 7 },
  { name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1868', flag: '🇹🇹', phoneLength: 7 },
  { name: 'Turks and Caicos Islands', code: 'TC', dialCode: '+1649', flag: '🇹🇨', phoneLength: 7 },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾', phoneLength: 8 },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪', phoneLength: 10 },

  // 🌏 Asia Pacific
  { name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺', phoneLength: 9 },
  { name: 'Bhutan', code: 'BT', dialCode: '+975', flag: '🇧🇹', phoneLength: 8 },
  { name: 'Brunei', code: 'BN', dialCode: '+673', flag: '🇧🇳', phoneLength: 7 },
  { name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭', phoneLength: 9 },
  { name: 'China mainland', code: 'CN', dialCode: '+86', flag: '🇨🇳', phoneLength: 11 },
  { name: 'Fiji', code: 'FJ', dialCode: '+679', flag: '🇫🇯', phoneLength: 7 },
  { name: 'Hong Kong', code: 'HK', dialCode: '+852', flag: '🇭🇰', phoneLength: 8 },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩', phoneLength: 10 },
  { name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵', phoneLength: 10 },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿', phoneLength: 10 },
  { name: 'Korea, Republic of', code: 'KR', dialCode: '+82', flag: '🇰🇷', phoneLength: 10 },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', flag: '🇰🇬', phoneLength: 9 },
  { name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦', phoneLength: 10 },
  { name: 'Macau', code: 'MO', dialCode: '+853', flag: '🇲🇴', phoneLength: 8 },
  { name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾', phoneLength: 9 },
  { name: 'Maldives', code: 'MV', dialCode: '+960', flag: '🇲🇻', phoneLength: 7 },
  { name: 'Micronesia', code: 'FM', dialCode: '+691', flag: '🇫🇲', phoneLength: 7 },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', flag: '🇲🇳', phoneLength: 8 },
  { name: 'Myanmar', code: 'MM', dialCode: '+95', flag: '🇲🇲', phoneLength: 9 },
  { name: 'Nauru', code: 'NR', dialCode: '+674', flag: '🇳🇷', phoneLength: 7 },
  { name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵', phoneLength: 10 },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿', phoneLength: 9 },
  { name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰', phoneLength: 10 },
  { name: 'Palau', code: 'PW', dialCode: '+680', flag: '🇵🇼', phoneLength: 7 },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', flag: '🇵🇬', phoneLength: 8 },
  { name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭', phoneLength: 10 },
  { name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬', phoneLength: 8 },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677', flag: '🇸🇧', phoneLength: 7 },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰', phoneLength: 9 },
  { name: 'Taiwan', code: 'TW', dialCode: '+886', flag: '🇹🇼', phoneLength: 9 },
  { name: 'Tajikistan', code: 'TJ', dialCode: '+992', flag: '🇹🇯', phoneLength: 9 },
  { name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭', phoneLength: 9 },
  { name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴', phoneLength: 7 },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993', flag: '🇹🇲', phoneLength: 8 },
  { name: 'Uzbekistan', code: 'UZ', dialCode: '+998', flag: '🇺🇿', phoneLength: 9 },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺', phoneLength: 7 },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳', phoneLength: 9 },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // United States
